### ISSUE TITLE
Get system stats

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively-cef#10]
cpu, gpu temp, load etc... to have interactive web wallpapers: https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data

WMI has limitations when reading gpu data etc..

It is easily possible using openhardwaremonitorlib: 
https://www.instructables.com/id/Using-Open-Hardware-Monitor-to-Get-CPU-Temperature/

Problem is to retrieve some data such as temperature program needs to run with admin rights.

**Comment by rocksdanister** [comment]
Alternatively I can just tell the user to run the 3rd party program and then read data from it instead.

**Comment by Poltergeisen** [comment]
I think that asking for administrator permissions would work well if the smartscreen issues could be resolved. If no admin is available for a user then the system functions could be disabled?

**Comment by rocksdanister** [comment]
It will always be optional and loaded only if requested by wallpaper similar to how audio data works.

Smartscreen might take some time, require hardware also to setup the certificate: https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-1022.html
